services:
  db:
    image: postgres:15
    container_name: store_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  api:
    build:
      context: ./store_api
      args:
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    container_name: store_api
    ports:
      - "4001:4001"
    depends_on:
      - db
    env_file:
      - .env 
    volumes:
      - ./store_api:/app
    command: sh -c "mix deps.get && mix ecto.create && mix ecto.migrate && mix run priv/repo/seeds.exs && mix phx.server"

volumes:
  postgres_data:
