services:
  db:
    image: postgres:15
    container_name: store_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  api:
    build:
      context: ./store_api
      args:
        GUARDIAN_SECRET_KEY: ${GUARDIAN_SECRET_KEY}
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    container_name: store_api
    ports:
      - "4001:4001"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      GUARDIAN_SECRET_KEY: ${GUARDIAN_SECRET_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      PHX_SERVER: true
    volumes:
      - ./store_api:/app

  frontend:
    build:
      context: ./frontend
    container_name: store_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    env_file:
      - .env
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  postgres_data:
